name: varun_s_application1
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.18.3 <3.10.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_login_facebook: ^1.6.2
  google_sign_in: ^5.0.7
  pin_code_fields: ^7.3.0
  sms_autofill: ^2.0.0
  pin_input_text_field: 4.1.0
  intl: ^0.17.0
  permission_handler: ^10.0.0
  images_picker: ^1.2.11
  camera: ^0.10.4
  video_player: ^2.6.1
  path_provider: ^2.0.14
  image_picker: ^0.8.7+4
  http: ^0.13.5
  dropdown_search: ^5.0.6
  dropdown_button2: ^2.1.0
  qr_code_scanner: ^1.0.1
  cupertino_icons: ^1.0.2
  pdf: ^3.10.0
  open_file: ^3.1.0
  printing:
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
